### ISSUE TITLE
Omx Player not working!!!

### ISSUE THREAD

**Issue by ProBlox42R** [jehutting/omxplayer-player#3]
## LOG
sudo python /home/hi/Music/omxplayer.py /home/hi/Music
dirname="/home/hi/Music"
pattern="*.mp3"
['/home/hi/Music/Eminem-The-real-Slim-Shady.mp3', '/home/hi/Music/Eminem-Venom-Remix-Audio.mp3', '/home/hi/Music/Eminem_-_Mockingbird-Hippopcharts.com.mp3', '/home/hi/Music/Eminem_-_Superman.mp3', '/home/hi/Music/Love the Way You Lie - Eminem ft. Rihanna 320(PagalWorld).mp3', '/home/hi/Music/Till I Collapse - Eminem(PagalWorld).mp3', '/home/hi/Music/Without-Me---Eminem(musicdownload.cc) (1).mp3']
DEBUG:__Button__:Play: initial state=0
DEBUG:__Button__:Previous: initial state=0
DEBUG:__Button__:Next: initial state=0
DEBUG:__Led__:Play: off
DEBUG:__OMXPlayer__:Full command=['omxplayer', '--no-osd', '/home/hi/Music/Eminem-The-real-Slim-Shady.mp3']
DEBUG:__OMXPlayer__:Waiting for running REAL OMXPlayer...
Exception in thread Thread-1 (run_in_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hi/Music/omxplayer.py", line 113, in run_in_thread
    self.process = subprocess.Popen(command,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'omxplayer'

**Comment by jehutting** [comment]
Hello @ProBlox42R 

The last line says it all
`FileNotFoundError: [Errno 2] No such file or directory: 'omxplayer'`

I suspect you are running an OS with omxplayer not (longer default) installed/supported, e.g. bullseye.
To see what OS you have installed you can run the command
`cat /etc/os-release`

In case omxplayer is not installed, have a google search on how to install it.
Be aware that sadly enough, omxplayer is deprecated in flavor of vlc.

**Comment by ProBlox42R** [comment]
I'm running rasberry pi os

**Comment by ProBlox42R** [comment]
:)

**Comment by jehutting** [comment]
That's fine.
Can you run the command
**cat /etc/os-release**
To check if omplayer is installed, just run the command
**omxplayer**

**Comment by ProBlox42R** [comment]
Ok
